### ISSUE TITLE
Got a Crash, admins said its the "sound file in mekanisim" What do i do?

### ISSUE THREAD

**Issue by CaptainDarkwolf** [kreezxil/better-than-minecolonies-getting-started#20] opened 2020-02-09 01:12 UTC
[crash-2020-02-07_20.29.14-client.txt](https://github.com/kreezxil/better-than-minecolonies-getting-started/files/4176336/crash-2020-02-07_20.29.14-client.txt)

**Comment by kreezxil** [comment] 2020-02-09 01:52
Welcome to the world of posting bugs. One of the things you must master. More steps for you but less steps for everyone who helps you in the future.

use a pasting services like https://gist.github.com

Let's go there first.

Then open that crash log up, and copy all the text in it.

You can do this keys on your keyboard, if you're using a mac, whereever I say ctrl  you should interpret that as command.

To copy all the text in the text file, when it is open, click in the box where the text is.

then hit CTRL A
then hit CTRL C

now got back to the gist paste
click in the big white box
then hit CTRL V

with your text now pasted there (pasting service, get it?)

click on the submit/ok button

the page will refresh and the address bard will change with random characters on the end, copy the whole thing (it's called an url)

paste that here or in chat or wherever someone asked you for log.

What this does is allow us to to click the link and it opens in our browsers without there being 6 to 10 extra steps for us. You do those extra steps just once and the rest of us get away with one click.

As a neophyte you'll be tasked with explaining to all newbs you meet without what a pasting service is and how to use it.

# that said, you don't have to do it for the thing on the top you posted already
I'll convert it int to a proper bug report.

**Comment by kreezxil** [comment] 2020-02-09 02:00
this is what it would look like https://gist.github.com/kreezxil/73b4506635fb59a2a1bba0e6412d1be5

Anyways, I've discovered that we're about 6 versions behind, I'll release an update to the pack tomorrow. If it continues to crash please post to the end of this report with the crash report but thru a pasting service.

**Comment by kreezxil** [comment] 2020-02-09 18:39
I don't know why I committed to t his, **MEKANISM** isn't even in this pack.

You either added Mekanism, or you posted to the wrong pack tracker. Probably caused by you going to whichever Discord sub channel on my discord you felt like rather than the right one.

Not really sorry if that feels like finger pointing, because that is finger pointing. I just updated BTMCGS to realize it doesn't even have Mekanism in it. You can imagine how I'm feeling.

You need to take the information I presented here and use it to fix your own pack or at least post in the right tracker.

**Comment by kreezxil** [comment] 2020-02-09 18:54
Looking at your crash report deeper @CaptainDarkwolf 

# this
# is
# not
# my
# pack
# one
# bit

You have galaxy and galacticraft in it

I don't use either of those two mods in any of my packs.

Did you confuse me with Dungeons, Dragons, and Space Shuttles?

**Comment by CaptainDarkwolf** [comment] 2020-02-10 17:31
It says right there that its your mod, this is where i
downloaded it from so maybe twitch is to blame here but i found your
discord on there and joined it to look for help.
![image](https://user-images.githubusercontent.com/60831749/74174170-64670800-4c2b-11ea-9ccc-6f5dc7faa085.png)

**Comment by kreezxil** [comment] 2020-02-10 20:48
except your crash report isn't for my pack.

if you have a crash in BTMCGS, click on the sprocket in the upper right of that page you just screenshotted, click on "open folder" then open the "crash-reports" folder and there will be the crash reports for my pack. not the other pack you gave for.

**Comment by kreezxil** [comment] 2020-02-10 20:49
and I have to say again.

Mekanism is not in this pack
neither is GalactiCraft
nor Extra Planets

**Comment by kreezxil** [comment] 2020-02-10 20:50
look at the crash report you gave me and look at the mods in the pack, they don't match.

**Comment by CaptainDarkwolf** [comment] 2020-02-10 23:21
Aah i might of sent the wrong one by mistake, okay i found a problem there
isnt a crash file at all so what im going to do is delete the game, every
little thing of it then reinstall it, might fix the problem

**Comment by CaptainDarkwolf** [comment] 2020-02-10 23:38
Nope didnt work, went into logs instead and found this not sure if these
help

[23:35:03] [main/INFO]: ModLauncher running: args [--username,
Capt_Darkwolf, --version, forge-28.2.0, --gameDir, C:\Users\Captain
Darkwolf\Twitch\Minecraft\Instances\Better Than Minecolonies Getting
Started, --assetsDir, C:\Users\Captain
Darkwolf\Twitch\Minecraft\Install\assets, --assetIndex, 1.14, --uuid,
451b48da0a6f44ad9cc2da9c4f34a3a6, --accessToken, ????????, --userType,
mojang, --versionType, release, --width, 1024, --height, 768,
--launchTarget, fmlclient, --fml.forgeVersion, 28.2.0, --fml.mcVersion,
1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion,
20190829.143755]
[23:35:03] [main/INFO]: ModLauncher 4.1.0+62+5bfa59b starting: java version
1.8.0_51 by Oracle Corporation
[23:35:04] [main/INFO]: Added Lets Encrypt root certificates as additional
trust
[23:35:04] [main/FATAL]: Failed to find Minecraft resource version
1.14.4-20190829.143755 at C:\Users\Captain
Darkwolf\Twitch\Minecraft\Install\libraries\net\minecraftforge\forge\1.14.4-28.2.0\forge-1.14.4-28.2.0-client.jar
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:
java.lang.RuntimeException: Missing minecraft resource!
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
net.minecraftforge.fml.loading.FMLCommonLaunchHandler$$Lambda$137/1462044018.accept(Unknown
Source)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:195)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:92)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$84/464887938.accept(Unknown
Source)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
java.util.HashMap$Values.forEach(HashMap.java:972)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[23:35:04] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at
cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by kreezxil** [comment] 2020-02-11 14:29
Now that you're running the right thing and you are accessing the right stuff.

Send me the entire latest.log and the crash-report if any, with an explanation of the issue.

use https://gist.github.com or any other pasting service you're comfortable with to send the logs.

**Comment by kreezxil** [comment] 2020-02-11 14:33
Please goto https://github.com/kreezxil/better-than-minecolonies-getting-started/issues/21 and continue the debugging thread with BTMCGS. 

Btw, did you even bother to update it since you got me to update it to begin with?

If you're using any launcher other than Twitch you won't be notified that there is an update.

in GD Launcher you must right click the pack and choose manage
on the next page choose modpack versions and finally choose the top one in the drop down.

Twitch is goofy too, it doesn't always say there is an update, however you can click the profile icon to entire to where you can see the mods, and then click on versions, check the box at the top, and hit ok at the bottom, the latest version of that pack will begin installing regardless.

**Closed as completed by kreezxil** 2020-02-11 14:33 UTC
